//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.BD {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Cnn : global::System.Configuration.ApplicationSettingsBase {
        
        private static Cnn defaultInstance = ((Cnn)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Cnn())));
        
        public static Cnn Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=201.87.129.114;Initial Catalog=sistecno;User ID=sa;Password=@oncetsis" +
            "12122014;")]
        public string Conn {
            get {
                return ((string)(this["Conn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.10.4;Initial Catalog=Grupologos;User ID=sa;Password=@logos090" +
            "22005$;")]
        public string ConnLogos {
            get {
                return ((string)(this["ConnLogos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=201.87.129.114;Initial Catalog=APP;User ID=sa;Password=@oncetsis12122" +
            "014;")]
        public string ConnApp {
            get {
                return ((string)(this["ConnApp"]));
            }
        }
    }
}
