//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendamentoDocumento
    {
        public int IdAgendamentoDocumento { get; set; }
        public int IdAgendamento { get; set; }
        public int IdDocumento { get; set; }
        public string StatusDoDocumento { get; set; }
        public string SituacaoDoDocumento { get; set; }
        public string NomeDoArquivo { get; set; }
        public Nullable<System.DateTime> DataGeracaoDoArquivo { get; set; }
    
        public virtual Agendamento Agendamento { get; set; }
        public virtual Documento Documento { get; set; }
    }
}
