//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendaRecebimento
    {
        public AgendaRecebimento()
        {
            this.Agendamento = new HashSet<Agendamento>();
        }
    
        public int IdAgendaRecebimento { get; set; }
        public int IdFilial { get; set; }
        public int IdDepositoPlantaLocalizacao { get; set; }
        public Nullable<int> IdAgendamento { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Hora { get; set; }
        public string Disponivel { get; set; }
    
        public virtual ICollection<Agendamento> Agendamento { get; set; }
        public virtual Agendamento Agendamento1 { get; set; }
        public virtual DepositoPlantaLocalizacao DepositoPlantaLocalizacao { get; set; }
        public virtual Filial Filial { get; set; }
    }
}
