//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ajuda
    {
        public int IDModuloOpcao { get; set; }
        public string Campo { get; set; }
        public string Ajuda1 { get; set; }
        public string AjudaUsuario { get; set; }
    
        public virtual ModuloOpcao ModuloOpcao { get; set; }
    }
}
