//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta
    {
        public Alerta()
        {
            this.CadastroContatoAlerta = new HashSet<CadastroContatoAlerta>();
            this.UsuarioAlerta = new HashSet<UsuarioAlerta>();
        }
    
        public int IDAlerta { get; set; }
        public string Descricao { get; set; }
        public string Rotina { get; set; }
        public Nullable<int> ExecutarEmMinutos { get; set; }
    
        public virtual ICollection<CadastroContatoAlerta> CadastroContatoAlerta { get; set; }
        public virtual ICollection<UsuarioAlerta> UsuarioAlerta { get; set; }
    }
}
