//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApoliceItem
    {
        public int IdApoliceItem { get; set; }
        public int IdApolice { get; set; }
        public Nullable<decimal> De { get; set; }
        public Nullable<decimal> Ate { get; set; }
        public string Produto { get; set; }
        public string Exigencias { get; set; }
        public string ExigeLiberacao { get; set; }
    }
}
