//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BairroFaixaDeCep
    {
        public int IDBairroFaixaDeCep { get; set; }
        public Nullable<int> IDBairro { get; set; }
        public string Inicial { get; set; }
        public string Final { get; set; }
    
        public virtual Bairro Bairro { get; set; }
    }
}
