//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BancoCarteira
    {
        public BancoCarteira()
        {
            this.BancoContaBloqueto = new HashSet<BancoContaBloqueto>();
        }
    
        public int IDBancoCarteira { get; set; }
        public int IDBanco { get; set; }
        public string Codigo { get; set; }
        public string Descricao { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual ICollection<BancoContaBloqueto> BancoContaBloqueto { get; set; }
    }
}
