//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco
    {
        public Banco()
        {
            this.BancoCarteira = new HashSet<BancoCarteira>();
            this.BancoConta = new HashSet<BancoConta>();
            this.BancoEspecie = new HashSet<BancoEspecie>();
            this.BancoInstrucao = new HashSet<BancoInstrucao>();
            this.BancoInstrucaoDeProtesto = new HashSet<BancoInstrucaoDeProtesto>();
            this.BancoOcorrenciaRemessa = new HashSet<BancoOcorrenciaRemessa>();
            this.BancoOcorrenciaRetorno = new HashSet<BancoOcorrenciaRetorno>();
            this.CadastroComplemento = new HashSet<CadastroComplemento>();
            this.Cheque = new HashSet<Cheque>();
        }
    
        public int IDBanco { get; set; }
        public int Digito { get; set; }
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DataDeCadastro { get; set; }
        public string Ativo { get; set; }
        public byte[] LogoTipo { get; set; }
        public Nullable<int> IDLeiauteCheque { get; set; }
        public Nullable<int> IDLeiauteBoleto { get; set; }
        public Nullable<int> IDPais { get; set; }
        public Nullable<int> DiasRetencao { get; set; }
        public Nullable<decimal> TaxaCobrancaSimples { get; set; }
    
        public virtual ICollection<BancoCarteira> BancoCarteira { get; set; }
        public virtual ICollection<BancoConta> BancoConta { get; set; }
        public virtual ICollection<BancoEspecie> BancoEspecie { get; set; }
        public virtual ICollection<BancoInstrucao> BancoInstrucao { get; set; }
        public virtual ICollection<BancoInstrucaoDeProtesto> BancoInstrucaoDeProtesto { get; set; }
        public virtual ICollection<BancoOcorrenciaRemessa> BancoOcorrenciaRemessa { get; set; }
        public virtual ICollection<BancoOcorrenciaRetorno> BancoOcorrenciaRetorno { get; set; }
        public virtual ICollection<CadastroComplemento> CadastroComplemento { get; set; }
        public virtual ICollection<Cheque> Cheque { get; set; }
    }
}
