//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE
    {
        public string CODIGO { get; set; }
        public string DESCRICAO { get; set; }
        public string CDA { get; set; }
        public Nullable<double> IDCDA { get; set; }
        public Nullable<double> SALDOATUAL { get; set; }
        public Nullable<double> SALDOCORRETO { get; set; }
        public bool F7 { get; set; }
    }
}
