//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bordero
    {
        public Bordero()
        {
            this.BorderoTituloDuplicata = new HashSet<BorderoTituloDuplicata>();
        }
    
        public int IDBordero { get; set; }
        public int IDFilial { get; set; }
        public string Tipo { get; set; }
        public int Numero { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> IdBancoConta { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public string Descricao { get; set; }
        public string Modalidade { get; set; }
        public string TipoDeAgendamento { get; set; }
        public string TipoDeMovimento { get; set; }
    
        public virtual Filial Filial { get; set; }
        public virtual ICollection<BorderoTituloDuplicata> BorderoTituloDuplicata { get; set; }
    }
}
