//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CheckList_Espacodisco
    {
        public string Drive { get; set; }
        public Nullable<int> Tamanho__MB_ { get; set; }
        public Nullable<int> Usado__MB_ { get; set; }
        public Nullable<int> Livre__MB_ { get; set; }
        public Nullable<int> Livre____ { get; set; }
        public Nullable<int> Usado____ { get; set; }
        public int Ocupado_SQL__MB_ { get; set; }
    }
}
