//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroReferencia
    {
        public int IDCadastroReferencia { get; set; }
        public int IDCadastro { get; set; }
        public string TipoDeReferencia { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Referencia { get; set; }
        public string Contato { get; set; }
        public string Observacao { get; set; }
    
        public virtual Cadastro Cadastro { get; set; }
    }
}
