//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public Cheque()
        {
            this.DtCheque = new HashSet<DtCheque>();
            this.MovimentacaoBancaria = new HashSet<MovimentacaoBancaria>();
        }
    
        public int IDCheque { get; set; }
        public Nullable<int> IDBancoConta { get; set; }
        public int IDBanco { get; set; }
        public string Numero { get; set; }
        public string Serie { get; set; }
        public System.DateTime DataDeEmissao { get; set; }
        public decimal Valor { get; set; }
        public decimal Saldo { get; set; }
        public string Situacao { get; set; }
        public string Portador { get; set; }
        public System.DateTime DataDeDisponibilidade { get; set; }
        public string PagarReceber { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual BancoConta BancoConta { get; set; }
        public virtual ICollection<DtCheque> DtCheque { get; set; }
        public virtual ICollection<MovimentacaoBancaria> MovimentacaoBancaria { get; set; }
    }
}
