//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIDADES
    {
        public Nullable<int> CD_UF { get; set; }
        public int CD_CIDADE { get; set; }
        public string DS_CIDADE_NOME { get; set; }
        public Nullable<double> CD_AREA { get; set; }
        public string CODIGO_IBGE { get; set; }
        public string UF { get; set; }
    }
}
