//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteMeta
    {
        public int IdClienteMeta { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public int Prazo { get; set; }
        public string Cor { get; set; }
        public decimal Percentual { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
