//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenciaPalletProdutoXXXXX
    {
        public int IdConferenciaPalletProduto { get; set; }
        public int IdConferenciaPallet { get; set; }
        public int IdProdutoEmbalagem { get; set; }
        public decimal Quantidade { get; set; }
        public string Tipo { get; set; }
    
        public virtual ConferenciaPallet ConferenciaPallet { get; set; }
        public virtual ProdutoEmbalagem ProdutoEmbalagem { get; set; }
    }
}
