//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenciaPallet
    {
        public ConferenciaPallet()
        {
            this.ConferenciaPalletDoc = new HashSet<ConferenciaPalletDoc>();
            this.ConferenciaPalletEntrada = new HashSet<ConferenciaPalletEntrada>();
            this.ConferenciaPalletEntradaLote = new HashSet<ConferenciaPalletEntradaLote>();
            this.ConferenciaPalletProdutoXXXXX = new HashSet<ConferenciaPalletProdutoXXXXX>();
        }
    
        public int IdConferenciaPallet { get; set; }
        public int IdConferencia { get; set; }
        public int IdPallet { get; set; }
        public int IdDepositoPlantaLocalizacao { get; set; }
    
        public virtual Conferencia Conferencia { get; set; }
        public virtual DepositoPlantaLocalizacao DepositoPlantaLocalizacao { get; set; }
        public virtual UnidadeDeArmazenagem UnidadeDeArmazenagem { get; set; }
        public virtual ICollection<ConferenciaPalletDoc> ConferenciaPalletDoc { get; set; }
        public virtual ICollection<ConferenciaPalletEntrada> ConferenciaPalletEntrada { get; set; }
        public virtual ICollection<ConferenciaPalletEntradaLote> ConferenciaPalletEntradaLote { get; set; }
        public virtual ICollection<ConferenciaPalletProdutoXXXXX> ConferenciaPalletProdutoXXXXX { get; set; }
    }
}
