//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenciaPalletEntradaLote
    {
        public int IdConferenciaPalletEntradaLote { get; set; }
        public int IdConferenciaPallet { get; set; }
        public int IdProdutoCliente { get; set; }
        public Nullable<int> IdProduto { get; set; }
        public Nullable<int> IdDocumentoItem { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public Nullable<decimal> Fator { get; set; }
        public string Lote { get; set; }
        public Nullable<System.DateTime> Validade { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
    
        public virtual ConferenciaPallet ConferenciaPallet { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual ProdutoCliente ProdutoCliente { get; set; }
    }
}
