//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenciaPalletDocVol
    {
        public ConferenciaPalletDocVol()
        {
            this.ConferenciaPalletDocVolItem = new HashSet<ConferenciaPalletDocVolItem>();
        }
    
        public int IdConferenciaPalletDocVol { get; set; }
        public int IdConferenciaPalletDoc { get; set; }
        public Nullable<int> IdVolume { get; set; }
    
        public virtual ConferenciaPalletDoc ConferenciaPalletDoc { get; set; }
        public virtual ICollection<ConferenciaPalletDocVolItem> ConferenciaPalletDocVolItem { get; set; }
    }
}
