//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContaDespesaItem
    {
        public int IdContaDespesaItem { get; set; }
        public int IdContaDespesa { get; set; }
        public Nullable<decimal> PercentualRateioCentroDeCusto { get; set; }
        public Nullable<decimal> PercentualRateioContaContabil { get; set; }
        public Nullable<int> IdContaContabilFilial { get; set; }
        public Nullable<int> IdCentroDeCustoFilial { get; set; }
        public Nullable<decimal> ValorRateioCentroDeCusto { get; set; }
        public Nullable<decimal> ValorRateioContaContabil { get; set; }
    
        public virtual ContaDespesa ContaDespesa { get; set; }
    }
}
