//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoObjeto
    {
        public DocumentoObjeto()
        {
            this.DocumentoObjetoOcorrencia = new HashSet<DocumentoObjetoOcorrencia>();
        }
    
        public int IdDocumentoObjeto { get; set; }
        public int IdDocumento { get; set; }
        public string Objeto { get; set; }
        public string Situacao { get; set; }
        public Nullable<int> Ordem { get; set; }
        public Nullable<int> Volumes { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual ICollection<DocumentoObjetoOcorrencia> DocumentoObjetoOcorrencia { get; set; }
    }
}
