//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoAteItem
    {
        public int IDDocumentoAteItem { get; set; }
        public int IDDocumentoAte { get; set; }
        public string TipoDocumento { get; set; }
        public Nullable<int> IDCidade { get; set; }
        public Nullable<int> IDEstado { get; set; }
        public Nullable<decimal> ValorDoc { get; set; }
        public string NumeroDoc { get; set; }
        public Nullable<int> IDCidadeColeta { get; set; }
        public Nullable<int> IDEstadoColeta { get; set; }
    }
}
