//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoOcorrencia
    {
        public DocumentoOcorrencia()
        {
            this.Documento = new HashSet<Documento>();
            this.DocumentoOcorrenciaArquivo = new HashSet<DocumentoOcorrenciaArquivo>();
            this.DocumentoOcorrenciaItem = new HashSet<DocumentoOcorrenciaItem>();
        }
    
        public int IDDocumentoOcorrencia { get; set; }
        public int IDDocumento { get; set; }
        public int IDFilial { get; set; }
        public Nullable<int> IDOcorrencia { get; set; }
        public Nullable<int> IDConhecimento { get; set; }
        public Nullable<int> IDRomaneio { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public Nullable<System.DateTime> DataOcorrencia { get; set; }
        public Nullable<System.DateTime> DataLancamento { get; set; }
        public string Descricao { get; set; }
        public string Pessoa { get; set; }
        public string CpfRg { get; set; }
        public string Sistema { get; set; }
        public string Senha { get; set; }
        public Nullable<int> IdOcorrenciaAndamento { get; set; }
        public string ArquivoDeIntegracao { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> IdOcorrenciaComprovei { get; set; }
    
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual Documento Documento1 { get; set; }
        public virtual Filial Filial { get; set; }
        public virtual Ocorrencia Ocorrencia { get; set; }
        public virtual Romaneio Romaneio { get; set; }
        public virtual ICollection<DocumentoOcorrenciaArquivo> DocumentoOcorrenciaArquivo { get; set; }
        public virtual ICollection<DocumentoOcorrenciaItem> DocumentoOcorrenciaItem { get; set; }
    }
}
