//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtCheque
    {
        public int IdDtCheque { get; set; }
        public int IdDt { get; set; }
        public int IdCheque { get; set; }
    
        public virtual Cheque Cheque { get; set; }
        public virtual DT DT { get; set; }
    }
}
