//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edi_Gerado
    {
        public int IdEdi_Gerado { get; set; }
        public Nullable<int> IdDocumentoItem { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
    }
}
