//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI_DocumentoRelacionado
    {
        public string EDI_Chave { get; set; }
        public string EDI_Motivo { get; set; }
        public Nullable<System.DateTime> EDI_Data { get; set; }
        public Nullable<int> IdDocumentoRelacionado { get; set; }
        public Nullable<int> IdDocumentoPai { get; set; }
        public Nullable<int> IdDocumentoFilho { get; set; }
        public Nullable<int> IdAgrupamento { get; set; }
        public Nullable<int> IdEDI_DocumentoRelacionado { get; set; }
    }
}
