//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdiControleDeArquivoLog
    {
        public int IdEdiControleDeArquivoLog { get; set; }
        public int IdEdiControleDeArquivo { get; set; }
        public string TipoDeRegistro { get; set; }
        public string Chave { get; set; }
        public Nullable<int> Linha { get; set; }
        public string Ocorrencia { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string NomeDoArquivo { get; set; }
    }
}
