//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDILayOutReg
    {
        public EDILayOutReg()
        {
            this.EDILayOutReg1 = new HashSet<EDILayOutReg>();
            this.EDILayOutRegCpo = new HashSet<EDILayOutRegCpo>();
            this.EDILayoutRegTabela = new HashSet<EDILayoutRegTabela>();
        }
    
        public int IDEDILayOutReg { get; set; }
        public int IDEDILayOut { get; set; }
        public string Descricao { get; set; }
        public int Ordem { get; set; }
        public Nullable<int> Pai { get; set; }
        public string Condicao { get; set; }
        public string TabelaChave { get; set; }
        public string CampoChave { get; set; }
        public string TabelaPai { get; set; }
        public string CampoPai { get; set; }
        public string Obrigatorio { get; set; }
    
        public virtual EDILayOut EDILayOut { get; set; }
        public virtual ICollection<EDILayOutReg> EDILayOutReg1 { get; set; }
        public virtual EDILayOutReg EDILayOutReg2 { get; set; }
        public virtual ICollection<EDILayOutRegCpo> EDILayOutRegCpo { get; set; }
        public virtual ICollection<EDILayoutRegTabela> EDILayoutRegTabela { get; set; }
    }
}
