//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDILayoutTabela
    {
        public int IDEDILayoutTabela { get; set; }
        public int IDEDILayout { get; set; }
        public string Tabela { get; set; }
        public Nullable<int> OrdemGravacao { get; set; }
        public string CampoUnico { get; set; }
    
        public virtual EDILayOut EDILayOut { get; set; }
    }
}
