//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoFaixaDeCep
    {
        public int IDEstadoFaixaDeCep { get; set; }
        public Nullable<int> IDEstado { get; set; }
        public string CepInicial { get; set; }
        public string CepFinal { get; set; }
    
        public virtual Estado Estado { get; set; }
    }
}
