//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int IdFuncionario { get; set; }
        public int IdFilial { get; set; }
        public int IdDepartamento { get; set; }
        public string Matricula { get; set; }
        public Nullable<System.DateTime> DataDeCadastro { get; set; }
        public Nullable<int> IDCentroDeCusto { get; set; }
        public Nullable<int> IDContaContabil { get; set; }
    
        public virtual CentroDeCusto CentroDeCusto { get; set; }
        public virtual ContaContabil ContaContabil { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Filial Filial { get; set; }
    }
}
