//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioUa
    {
        public int IdInventarioUa { get; set; }
        public int IdInventarioContagem { get; set; }
        public int IdUnidadeDeArmazenagemLote { get; set; }
        public string Status { get; set; }
    
        public virtual InventarioContagem InventarioContagem { get; set; }
        public virtual UnidadeDeArmazenagemLote UnidadeDeArmazenagemLote { get; set; }
    }
}
