//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public Inventario()
        {
            this.InventarioContagem = new HashSet<InventarioContagem>();
        }
    
        public int IdInventario { get; set; }
        public int IdFilial { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Situacao { get; set; }
        public string Descricao { get; set; }
        public string TipoDeInventario { get; set; }
        public string SolicitarUA { get; set; }
        public Nullable<int> PosicoesContadas { get; set; }
        public Nullable<int> PosicoesCorretas { get; set; }
        public Nullable<int> PosicoesContadasABC { get; set; }
        public Nullable<int> PosicoesCorretasABC { get; set; }
        public Nullable<int> SKUCorretos { get; set; }
        public Nullable<int> SKUTotal { get; set; }
        public Nullable<int> IdCda { get; set; }
    
        public virtual Cadastro Cadastro { get; set; }
        public virtual Filial Filial { get; set; }
        public virtual ICollection<InventarioContagem> InventarioContagem { get; set; }
    }
}
