//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIIRWIN_V2
    {
        public int IdKPIIRWIN { get; set; }
        public string Chave { get; set; }
        public string Descricao { get; set; }
        public string DescricaoUnidadeDeMedida { get; set; }
        public string DescricaoTarguet { get; set; }
        public Nullable<decimal> Target { get; set; }
        public string UnidadeTarget { get; set; }
        public string Calculado { get; set; }
        public Nullable<decimal> Ordem { get; set; }
    }
}
