//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lancamento
    {
        public int IdLancamento { get; set; }
        public Nullable<int> IdDocumentoOrigem { get; set; }
        public string Tabela { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Ativo { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<System.DateTime> DataLancamento { get; set; }
    }
}
