//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenciamentoMes
    {
        public int IdLicenciamentoMes { get; set; }
        public int IdLicenciamento { get; set; }
        public string FinalDaPlaca { get; set; }
        public string Mes { get; set; }
    
        public virtual Licenciamento Licenciamento { get; set; }
    }
}
