//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogComprovei
    {
        public int IdDocumento { get; set; }
        public string Chave { get; set; }
        public System.DateTime DataHora { get; set; }
        public string Resultado { get; set; }
        public string XML { get; set; }
    }
}
