//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginPerfil
    {
        public LoginPerfil()
        {
            this.LoginPerfilPermissao = new HashSet<LoginPerfilPermissao>();
        }
    
        public int IDLoginPerfil { get; set; }
        public int IDGrupo { get; set; }
        public string Descricao { get; set; }
        public string CriaUsuario { get; set; }
        public string Administrador { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual ICollection<LoginPerfilPermissao> LoginPerfilPermissao { get; set; }
    }
}
