//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapa
    {
        public Mapa()
        {
            this.MovimentacaoRomaneioItem = new HashSet<MovimentacaoRomaneioItem>();
        }
    
        public int IDMapa { get; set; }
        public int IDFilial { get; set; }
        public int IDUsuario { get; set; }
        public Nullable<int> IDUsuarioProcessamento { get; set; }
        public int Numero { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> DataDeCadastro { get; set; }
        public string EstoqueProcessado { get; set; }
        public Nullable<System.DateTime> DataDeProcessamento { get; set; }
        public string Ativo { get; set; }
        public string TIPO { get; set; }
        public string Impresso { get; set; }
        public Nullable<System.DateTime> DataDeImpressao { get; set; }
    
        public virtual Filial Filial { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<MovimentacaoRomaneioItem> MovimentacaoRomaneioItem { get; set; }
    }
}
