//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuCliente
    {
        public int IdMenuCliente { get; set; }
        public int IdCliente { get; set; }
        public int IdModuloOpcao { get; set; }
        public string Nome { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ModuloOpcao ModuloOpcao { get; set; }
    }
}
