//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoedaCotacao
    {
        public int IDMoedaCotacao { get; set; }
        public int IDMoeda { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Valor { get; set; }
    
        public virtual Moeda Moeda { get; set; }
    }
}
