//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motorista
    {
        public Motorista()
        {
            this.DT = new HashSet<DT>();
            this.DT1 = new HashSet<DT>();
            this.MotoristaFilial = new HashSet<MotoristaFilial>();
            this.MotoristaHistorico = new HashSet<MotoristaHistorico>();
            this.Veiculo = new HashSet<Veiculo>();
        }
    
        public int IDMotorista { get; set; }
        public string CarteiraDeHabilitacao { get; set; }
        public Nullable<System.DateTime> ValidadeDaHabilitacao { get; set; }
        public Nullable<System.DateTime> DataDaPrimeiraHabilitacao { get; set; }
        public string Categoria { get; set; }
        public Nullable<System.DateTime> DataDeNascimento { get; set; }
        public string IDCidadeNascimento { get; set; }
        public string NomeDoPai { get; set; }
        public string NomeDaMae { get; set; }
        public string Conjuge { get; set; }
        public Nullable<decimal> VitimaDeRouboQuantidade { get; set; }
        public Nullable<decimal> SofreuAcidadeQuantidade { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<System.DateTime> DataDeCadastro { get; set; }
        public Nullable<decimal> CarregamentoAutorizadoAte { get; set; }
        public Nullable<System.DateTime> VencimentoNoGerenciadorDeRisco { get; set; }
        public Nullable<decimal> AliquotaSestSenat { get; set; }
        public string VinculoComAEmpresa { get; set; }
        public string NumeroPancard { get; set; }
        public string Ativo { get; set; }
        public string Liberado { get; set; }
        public string MOPP { get; set; }
        public Nullable<System.DateTime> AguardandoLiberacao { get; set; }
        public Nullable<System.DateTime> VencimentoPancary { get; set; }
        public Nullable<System.DateTime> VencimentoBrasilrisk { get; set; }
        public Nullable<System.DateTime> VencimentoBuonny { get; set; }
        public Nullable<System.DateTime> DataDeBloqueio { get; set; }
        public string NumeroRegistroCNH { get; set; }
        public string NumeroInss { get; set; }
        public string Origem { get; set; }
        public string RecolheINSS { get; set; }
        public string RecolheIRRF { get; set; }
        public string RecolheSESTSENAT { get; set; }
        public string LocalRG { get; set; }
        public string LocalEmissaoRG { get; set; }
        public string Senha { get; set; }
    
        public virtual ICollection<DT> DT { get; set; }
        public virtual ICollection<DT> DT1 { get; set; }
        public virtual ICollection<MotoristaFilial> MotoristaFilial { get; set; }
        public virtual ICollection<MotoristaHistorico> MotoristaHistorico { get; set; }
        public virtual ICollection<Veiculo> Veiculo { get; set; }
    }
}
