//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OcorrenciaDePara
    {
        public int IdOcorrenciaDePara { get; set; }
        public int IdOcorrencia { get; set; }
        public Nullable<int> CodigoDoCliente { get; set; }
        public string Codigo { get; set; }
        public string Descricao { get; set; }
    
        public virtual Ocorrencia Ocorrencia { get; set; }
    }
}
