//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OcorrenciaCodigo
    {
        public int IDOcorrenciaCodigo { get; set; }
        public int IDOcorrencia { get; set; }
        public int IDOcorrenciaSerie { get; set; }
        public string Codigo { get; set; }
        public string Nome { get; set; }
    
        public virtual Ocorrencia Ocorrencia { get; set; }
        public virtual OcorrenciaSerie OcorrenciaSerie { get; set; }
    }
}
