//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public Pais()
        {
            this.Estado = new HashSet<Estado>();
            this.Moeda = new HashSet<Moeda>();
            this.RegiaoItem = new HashSet<RegiaoItem>();
        }
    
        public int IDPais { get; set; }
        public string Sigla { get; set; }
        public string Sigla1 { get; set; }
        public string Nome { get; set; }
        public string CodigoDoBacen { get; set; }
    
        public virtual ICollection<Estado> Estado { get; set; }
        public virtual ICollection<Moeda> Moeda { get; set; }
        public virtual ICollection<RegiaoItem> RegiaoItem { get; set; }
    }
}
