//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pallet
    {
        public Pallet()
        {
            this.PalletDocumento = new HashSet<PalletDocumento>();
        }
    
        public int IdPallet { get; set; }
        public Nullable<int> IdRomaneio { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> IdUsuarioCarregamento { get; set; }
        public Nullable<System.DateTime> DataDeAbertura { get; set; }
        public Nullable<System.DateTime> DataDeFechamento { get; set; }
        public Nullable<System.DateTime> DataDeAlteracao { get; set; }
        public Nullable<System.DateTime> InicioCarregamento { get; set; }
        public Nullable<System.DateTime> FinalCarregamento { get; set; }
        public Nullable<System.DateTime> ReAberturaDoPallet { get; set; }
        public Nullable<int> ReaberturaDoPalletIdUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual ICollection<PalletDocumento> PalletDocumento { get; set; }
        public virtual UnidadeDeArmazenagem UnidadeDeArmazenagem { get; set; }
    }
}
