//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PalletDocumento
    {
        public PalletDocumento()
        {
            this.PalletDocumentoItem = new HashSet<PalletDocumentoItem>();
        }
    
        public int IdPalletDocumento { get; set; }
        public int IdPallet { get; set; }
        public int IdUADocumento { get; set; }
        public int IdDocumento { get; set; }
        public Nullable<int> IdRomaneio { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> Inicio { get; set; }
        public Nullable<System.DateTime> Final { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual Pallet Pallet { get; set; }
        public virtual UnidadeDeArmazenagem UnidadeDeArmazenagem { get; set; }
        public virtual ICollection<PalletDocumentoItem> PalletDocumentoItem { get; set; }
        public virtual Romaneio Romaneio { get; set; }
    }
}
