//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoEmbalagem
    {
        public ProdutoEmbalagem()
        {
            this.ConferenciaPalletProdutoXXXXX = new HashSet<ConferenciaPalletProdutoXXXXX>();
            this.InventarioContagemProduto = new HashSet<InventarioContagemProduto>();
            this.Lote = new HashSet<Lote>();
            this.MovimentacaoRomaneioItem = new HashSet<MovimentacaoRomaneioItem>();
            this.ProdutoEmbalagem1 = new HashSet<ProdutoEmbalagem>();
            this.RomaneioDocumentoConferencia = new HashSet<RomaneioDocumentoConferencia>();
        }
    
        public int IDProdutoEmbalagem { get; set; }
        public int IDProdutoCliente { get; set; }
        public int IDProduto { get; set; }
        public Nullable<int> IDProdutoInterno { get; set; }
        public string Conteudo { get; set; }
        public decimal UnidadeDoCliente { get; set; }
        public Nullable<decimal> UnidadeLogistica { get; set; }
        public string UnidadeDeMedida { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
        public Nullable<System.DateTime> DataDeCadastro { get; set; }
        public string Ativo { get; set; }
        public Nullable<int> UniFor { get; set; }
        public Nullable<int> UniCli { get; set; }
        public Nullable<System.DateTime> DataUltimaAlteracao { get; set; }
        public string ArquivoQueAlterou { get; set; }
        public string OperadorParaConversao { get; set; }
        public string DumEan { get; set; }
        public Nullable<System.DateTime> DadosLogisticos { get; set; }
    
        public virtual ICollection<ConferenciaPalletProdutoXXXXX> ConferenciaPalletProdutoXXXXX { get; set; }
        public virtual ICollection<InventarioContagemProduto> InventarioContagemProduto { get; set; }
        public virtual ICollection<Lote> Lote { get; set; }
        public virtual ICollection<MovimentacaoRomaneioItem> MovimentacaoRomaneioItem { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual ProdutoCliente ProdutoCliente { get; set; }
        public virtual ICollection<ProdutoEmbalagem> ProdutoEmbalagem1 { get; set; }
        public virtual ProdutoEmbalagem ProdutoEmbalagem2 { get; set; }
        public virtual ICollection<RomaneioDocumentoConferencia> RomaneioDocumentoConferencia { get; set; }
    }
}
