//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoFoto
    {
        public int IDProdutoFoto { get; set; }
        public int IDProduto { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
