//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoCliente
    {
        public ProdutoCliente()
        {
            this.ConferenciaPalletDocVolItem = new HashSet<ConferenciaPalletDocVolItem>();
            this.ConferenciaPalletEntrada = new HashSet<ConferenciaPalletEntrada>();
            this.ConferenciaPalletEntradaLote = new HashSet<ConferenciaPalletEntradaLote>();
            this.DepositoPlantaLocalizacaoRegra = new HashSet<DepositoPlantaLocalizacaoRegra>();
            this.Estoque = new HashSet<Estoque>();
            this.InventarioContagemProduto = new HashSet<InventarioContagemProduto>();
            this.Lote = new HashSet<Lote>();
            this.ProdutoClienteAvaria = new HashSet<ProdutoClienteAvaria>();
            this.ProdutoClienteRegra = new HashSet<ProdutoClienteRegra>();
            this.ProdutoEmbalagem = new HashSet<ProdutoEmbalagem>();
            this.ProdutoEstrutura = new HashSet<ProdutoEstrutura>();
            this.ProdutoEstrutura1 = new HashSet<ProdutoEstrutura>();
            this.RomaneioDocumentoConferencia = new HashSet<RomaneioDocumentoConferencia>();
        }
    
        public int IDProdutoCliente { get; set; }
        public int IDCliente { get; set; }
        public Nullable<int> IDGrupoDeProduto { get; set; }
        public Nullable<int> IDDepositoPlantaLocalizacao { get; set; }
        public Nullable<int> IDClienteTipoDeMaterial { get; set; }
        public Nullable<int> IDUnidadeDeMedida { get; set; }
        public Nullable<int> IDContaContabilCredito { get; set; }
        public Nullable<int> IDContaContabilDebito { get; set; }
        public Nullable<int> IDCentroDeCustoCredito { get; set; }
        public Nullable<int> IDCentroDeCustoDebito { get; set; }
        public Nullable<int> IDCfop { get; set; }
        public string Codigo { get; set; }
        public string CodigoDoCliente { get; set; }
        public string Descricao { get; set; }
        public string DesmembraNaNF { get; set; }
        public string MetodoDeMovimentacao { get; set; }
        public string SolicitarDataDeValidade { get; set; }
        public Nullable<decimal> SaldoMinimo { get; set; }
        public Nullable<decimal> ConsumoMensal { get; set; }
        public Nullable<decimal> Ressuprimento { get; set; }
        public Nullable<decimal> UnidadeDoFornecedor { get; set; }
        public Nullable<decimal> UnidadeDoCliente { get; set; }
        public Nullable<System.DateTime> DataLimiteDeUso { get; set; }
        public string IsentoDeICMS { get; set; }
        public Nullable<decimal> ReducaoDeICMS { get; set; }
        public string DecretoDoICMS { get; set; }
        public Nullable<System.DateTime> DataDeCadastro { get; set; }
        public Nullable<decimal> Lastro { get; set; }
        public Nullable<decimal> Altura { get; set; }
        public string Ativo { get; set; }
        public string GrupoDeProdutoCliente { get; set; }
        public string CodigoNBM { get; set; }
        public string CodigoNCM { get; set; }
        public Nullable<int> CodigoGenero { get; set; }
        public Nullable<decimal> UnidadeDoFornecedorAlterado { get; set; }
        public Nullable<decimal> UnidadeDoClienteAlterada { get; set; }
        public Nullable<System.DateTime> DataAlteracaoDaUnidade { get; set; }
        public string NomeDoArquivo { get; set; }
        public Nullable<int> IDFornecedor { get; set; }
        public string Marca { get; set; }
        public Nullable<int> FatorUsoPosicaoPallet { get; set; }
        public Nullable<int> ShelfLife { get; set; }
        public Nullable<int> IdContaContabil { get; set; }
        public Nullable<int> IdCentroDeCusto { get; set; }
        public string CodigoDoFornecedor { get; set; }
        public string OrigemDaMercadoria { get; set; }
        public Nullable<decimal> SLDEntrada { get; set; }
        public Nullable<decimal> SLDRetorno { get; set; }
        public Nullable<decimal> SLDARetornar { get; set; }
        public Nullable<decimal> SLDUA { get; set; }
        public string InseridoPor { get; set; }
    
        public virtual CentroDeCusto CentroDeCusto { get; set; }
        public virtual CentroDeCusto CentroDeCusto1 { get; set; }
        public virtual Cfop Cfop { get; set; }
        public virtual ClienteTipoDeMaterial ClienteTipoDeMaterial { get; set; }
        public virtual ICollection<ConferenciaPalletDocVolItem> ConferenciaPalletDocVolItem { get; set; }
        public virtual ICollection<ConferenciaPalletEntrada> ConferenciaPalletEntrada { get; set; }
        public virtual ICollection<ConferenciaPalletEntradaLote> ConferenciaPalletEntradaLote { get; set; }
        public virtual ContaContabil ContaContabil { get; set; }
        public virtual ContaContabil ContaContabil1 { get; set; }
        public virtual DepositoPlantaLocalizacao DepositoPlantaLocalizacao { get; set; }
        public virtual ICollection<DepositoPlantaLocalizacaoRegra> DepositoPlantaLocalizacaoRegra { get; set; }
        public virtual ICollection<Estoque> Estoque { get; set; }
        public virtual GrupoDeProduto GrupoDeProduto { get; set; }
        public virtual ICollection<InventarioContagemProduto> InventarioContagemProduto { get; set; }
        public virtual ICollection<Lote> Lote { get; set; }
        public virtual UnidadeDeMedida UnidadeDeMedida { get; set; }
        public virtual ICollection<ProdutoClienteAvaria> ProdutoClienteAvaria { get; set; }
        public virtual ICollection<ProdutoClienteRegra> ProdutoClienteRegra { get; set; }
        public virtual ICollection<ProdutoEmbalagem> ProdutoEmbalagem { get; set; }
        public virtual ICollection<ProdutoEstrutura> ProdutoEstrutura { get; set; }
        public virtual ICollection<ProdutoEstrutura> ProdutoEstrutura1 { get; set; }
        public virtual ICollection<RomaneioDocumentoConferencia> RomaneioDocumentoConferencia { get; set; }
    }
}
