//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto
    {
        public Projeto()
        {
            this.ProjetoArquivo = new HashSet<ProjetoArquivo>();
            this.ProjetoFilial = new HashSet<ProjetoFilial>();
            this.ProjetoItem = new HashSet<ProjetoItem>();
            this.ProjetoProducao = new HashSet<ProjetoProducao>();
        }
    
        public int IdProjeto { get; set; }
        public int IdFilial { get; set; }
        public string Nome { get; set; }
        public string ContatoCliente { get; set; }
        public string ContatoContratado { get; set; }
        public string UtilizaAreaClimatizada { get; set; }
        public Nullable<System.DateTime> InicioDaProducao { get; set; }
        public Nullable<System.DateTime> FinalDaProducao { get; set; }
        public Nullable<System.DateTime> InicioDaEntrega { get; set; }
        public Nullable<System.DateTime> FinalDaEntrega { get; set; }
        public Nullable<int> TotalDeKits { get; set; }
        public Nullable<int> FatorPorCaixa { get; set; }
        public Nullable<int> FatorPorPallet { get; set; }
        public Nullable<decimal> PesoPorKit { get; set; }
        public Nullable<decimal> FretePorKit { get; set; }
        public Nullable<decimal> TempoDeProducao { get; set; }
        public Nullable<int> Turnos { get; set; }
        public Nullable<int> PessoasPorTurno { get; set; }
        public Nullable<int> MaoDeObra { get; set; }
        public string Status { get; set; }
        public string Edi { get; set; }
        public string DigitalizarComprovante { get; set; }
        public string EmitirCTRC { get; set; }
        public string EmitirNotaFiscalServico { get; set; }
        public string FormaFaturamento { get; set; }
        public string Vencimento { get; set; }
        public string OrigemDaColeta { get; set; }
        public string ValorPorColeta { get; set; }
        public string PlanejamentoDeTransferencia { get; set; }
        public string Observacao { get; set; }
    
        public virtual Filial Filial { get; set; }
        public virtual ICollection<ProjetoArquivo> ProjetoArquivo { get; set; }
        public virtual ICollection<ProjetoFilial> ProjetoFilial { get; set; }
        public virtual ICollection<ProjetoItem> ProjetoItem { get; set; }
        public virtual ICollection<ProjetoProducao> ProjetoProducao { get; set; }
    }
}
