//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjetoItem
    {
        public int IdProjetoItem { get; set; }
        public int IdProjeto { get; set; }
        public string Codigo { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public Nullable<decimal> QuantidadeRecebida { get; set; }
        public Nullable<System.DateTime> UltimoRecebimento { get; set; }
    
        public virtual Projeto Projeto { get; set; }
    }
}
