//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReposicaoRogeVolume
    {
        public int IdReposicaoRogeVolume { get; set; }
        public Nullable<int> IdResposicaoRoge { get; set; }
        public string CodigoDeBarras { get; set; }
        public string Conferido { get; set; }
        public Nullable<System.DateTime> DataDaInclusao { get; set; }
        public Nullable<System.DateTime> DataConferido { get; set; }
    
        public virtual ReposicaoRoge ReposicaoRoge { get; set; }
    }
}
