//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReposicaoRoge
    {
        public ReposicaoRoge()
        {
            this.ReposicaoRogeItem = new HashSet<ReposicaoRogeItem>();
            this.ReposicaoRogeVolume = new HashSet<ReposicaoRogeVolume>();
        }
    
        public int IdReposicaoRoge { get; set; }
        public string Chave { get; set; }
        public string IdNota { get; set; }
        public string CodigoRegiao { get; set; }
        public string NomeRegiao { get; set; }
        public Nullable<System.DateTime> DataDaInclusao { get; set; }
        public string UsuarioColetor { get; set; }
        public Nullable<System.DateTime> DataColetor { get; set; }
        public string UsuarioEnvioRoge { get; set; }
        public Nullable<System.DateTime> DataEnvioRoge { get; set; }
        public string CodigoEnvioRoge { get; set; }
        public string DescricaoEnvioRoge { get; set; }
        public Nullable<int> QuantidadeDeProduto { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Inicio { get; set; }
        public Nullable<System.DateTime> Fim { get; set; }
        public string ClienteEspecial { get; set; }
        public string UsuarioEnvioAuditoria { get; set; }
        public Nullable<System.DateTime> DataEnvioAuditoria { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> MercadoriaRecebida { get; set; }
        public string UsuarioMercadoriaRecebida { get; set; }
        public string StatusMercadoriaRecebida { get; set; }
        public string Observacao { get; set; }
    
        public virtual ICollection<ReposicaoRogeItem> ReposicaoRogeItem { get; set; }
        public virtual ICollection<ReposicaoRogeVolume> ReposicaoRogeVolume { get; set; }
    }
}
