//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisicaoDeMaterial
    {
        public RequisicaoDeMaterial()
        {
            this.EstoqueComprasMov = new HashSet<EstoqueComprasMov>();
            this.RequisicaoDeMaterialItem = new HashSet<RequisicaoDeMaterialItem>();
        }
    
        public int IDRequisicaoDeMaterial { get; set; }
        public int IDFilial { get; set; }
        public int IDUsuarioCompra { get; set; }
        public Nullable<int> IDUnidadeDeNegocios { get; set; }
        public System.DateTime DataDeSolicitacao { get; set; }
        public string Status { get; set; }
        public string Ativo { get; set; }
        public Nullable<System.DateTime> PrevisaoDeEntrega { get; set; }
        public string TipoDocumento { get; set; }
        public int IDCentroDeCustoFilial { get; set; }
        public Nullable<int> IdProjeto { get; set; }
        public string Impresso { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public string Prioridade { get; set; }
    
        public virtual ICollection<EstoqueComprasMov> EstoqueComprasMov { get; set; }
        public virtual ICollection<RequisicaoDeMaterialItem> RequisicaoDeMaterialItem { get; set; }
    }
}
