//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respostas
    {
        public int IDUsuario { get; set; }
        public string Formulario { get; set; }
        public string Componente { get; set; }
        public string Propriedade { get; set; }
        public Nullable<byte> Linha { get; set; }
        public string Valor { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
