//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RomaneioDocumentoItem
    {
        public int IDRomaneioDocumentoItem { get; set; }
        public int IDRomaneioDocumento { get; set; }
        public int IDDocumentoItem { get; set; }
        public decimal Quantidade { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> QuantidadeUnidadeEstoque { get; set; }
    
        public virtual DocumentoItem DocumentoItem { get; set; }
    }
}
