//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoteirizacaoTipo
    {
        public RoteirizacaoTipo()
        {
            this.RegiaoItem = new HashSet<RegiaoItem>();
        }
    
        public int IDRoteirizacaoTipo { get; set; }
        public decimal Ordem { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<RegiaoItem> RegiaoItem { get; set; }
    }
}
