//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelaDeFrete
    {
        public TabelaDeFrete()
        {
            this.Regiao = new HashSet<Regiao>();
            this.UsuarioDeTabelaDeFrete = new HashSet<UsuarioDeTabelaDeFrete>();
            this.TabelaDeFreteProduto = new HashSet<TabelaDeFreteProduto>();
            this.TabelaDeFreteRota = new HashSet<TabelaDeFreteRota>();
            this.TabelaDeFreteVigencia = new HashSet<TabelaDeFreteVigencia>();
        }
    
        public int IDTabelaDeFrete { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataDeCadastro { get; set; }
        public string TipoDeTabela { get; set; }
        public string Ativo { get; set; }
        public string TipoDeCalculo { get; set; }
    
        public virtual ICollection<Regiao> Regiao { get; set; }
        public virtual ICollection<UsuarioDeTabelaDeFrete> UsuarioDeTabelaDeFrete { get; set; }
        public virtual ICollection<TabelaDeFreteProduto> TabelaDeFreteProduto { get; set; }
        public virtual ICollection<TabelaDeFreteRota> TabelaDeFreteRota { get; set; }
        public virtual ICollection<TabelaDeFreteVigencia> TabelaDeFreteVigencia { get; set; }
    }
}
