//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TES
    {
        public TES()
        {
            this.TESCFOP = new HashSet<TESCFOP>();
            this.TESControle = new HashSet<TESControle>();
        }
    
        public int IDTES { get; set; }
        public string Descricao { get; set; }
        public string Aplicacao { get; set; }
        public string TipoDeDocumento { get; set; }
        public string EntradaSaida { get; set; }
        public string TipoDeServico { get; set; }
        public string GeraDuplicata { get; set; }
        public string GeraRomaneio { get; set; }
        public string GeraDocumento { get; set; }
        public string RequerDocumentoDeOrigem { get; set; }
        public string CalculaICMS { get; set; }
        public string CalculaIPI { get; set; }
        public string DestacaIPI { get; set; }
        public string CalculaISS { get; set; }
        public string CalculaPIS { get; set; }
        public string CalculaCOFINS { get; set; }
        public string CalculaCSLL { get; set; }
        public string AtualizaEstoque { get; set; }
        public string CreditaICMS { get; set; }
        public string CreditaIPI { get; set; }
        public string IPINaBaseICMS { get; set; }
        public Nullable<decimal> ReducaoICMS { get; set; }
        public Nullable<decimal> ReducaoIPI { get; set; }
        public Nullable<decimal> ReducaoISS { get; set; }
        public string IPISobreFrete { get; set; }
        public string PoderDeTerceiros { get; set; }
        public string DiferencaICMS { get; set; }
        public string LivroICMS { get; set; }
        public string LivroIPI { get; set; }
        public Nullable<System.DateTime> DataDeCadastro { get; set; }
        public Nullable<int> IDOcorrencia { get; set; }
        public string ConsideraOM { get; set; }
        public Nullable<int> IDLocal { get; set; }
        public string Ativo { get; set; }
        public string Sistema { get; set; }
        public string OrigemMovimentacao { get; set; }
        public string CalculaFrete { get; set; }
        public string MovimentaEstoque { get; set; }
        public string LoteEntradaSaida { get; set; }
    
        public virtual Ocorrencia Ocorrencia { get; set; }
        public virtual ICollection<TESCFOP> TESCFOP { get; set; }
        public virtual ICollection<TESControle> TESControle { get; set; }
    }
}
