//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TituloDuplicataRemessa
    {
        public int IdTituloDuplicataRemessa { get; set; }
        public int IdTituloDuplicata { get; set; }
        public int IDBancoOcorrenciaRemessa { get; set; }
        public Nullable<System.DateTime> DataMovimento { get; set; }
        public Nullable<System.DateTime> DataDeEnvio { get; set; }
        public Nullable<int> IdUsuarioQueEnviou { get; set; }
        public string Situacao { get; set; }
    
        public virtual BancoOcorrenciaRemessa BancoOcorrenciaRemessa { get; set; }
        public virtual TituloDuplicata TituloDuplicata { get; set; }
    }
}
