//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TituloItem
    {
        public int IdTituloItem { get; set; }
        public int IdTitulo { get; set; }
        public int Parcela { get; set; }
        public decimal Valor { get; set; }
    }
}
