//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadeDeArmazenagemAgrup
    {
        public int IDUnidadeDeArmazenagemAgrup { get; set; }
        public int IDUnidadeDeArmazenagem { get; set; }
        public int Agrupamento { get; set; }
    
        public virtual UnidadeDeArmazenagem UnidadeDeArmazenagem { get; set; }
    }
}
