//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadeDeArmazenagem
    {
        public UnidadeDeArmazenagem()
        {
            this.ConferenciaPallet = new HashSet<ConferenciaPallet>();
            this.InventarioContagemProduto = new HashSet<InventarioContagemProduto>();
            this.MovimentacaoRomaneioItem = new HashSet<MovimentacaoRomaneioItem>();
            this.PalletDocumento = new HashSet<PalletDocumento>();
            this.UnidadeDeArmazenagemAgrup = new HashSet<UnidadeDeArmazenagemAgrup>();
            this.UnidadeDeArmazenagemLote = new HashSet<UnidadeDeArmazenagemLote>();
        }
    
        public int IDUnidadeDeArmazenagem { get; set; }
        public int IDFilial { get; set; }
        public int IDDepositoPlantaLocalizacao { get; set; }
        public Nullable<System.DateTime> Impressao { get; set; }
    
        public virtual ICollection<ConferenciaPallet> ConferenciaPallet { get; set; }
        public virtual DepositoPlantaLocalizacao DepositoPlantaLocalizacao { get; set; }
        public virtual Filial Filial { get; set; }
        public virtual ICollection<InventarioContagemProduto> InventarioContagemProduto { get; set; }
        public virtual ICollection<MovimentacaoRomaneioItem> MovimentacaoRomaneioItem { get; set; }
        public virtual Pallet Pallet { get; set; }
        public virtual ICollection<PalletDocumento> PalletDocumento { get; set; }
        public virtual ICollection<UnidadeDeArmazenagemAgrup> UnidadeDeArmazenagemAgrup { get; set; }
        public virtual ICollection<UnidadeDeArmazenagemLote> UnidadeDeArmazenagemLote { get; set; }
    }
}
