//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadeDeArmazenagemMov
    {
        public int IdUnidadeDeArmazenagemMov { get; set; }
        public int IdUnidadeDeArmazenagem { get; set; }
        public Nullable<int> IdEnderecoOrigem { get; set; }
        public Nullable<int> IdEnderecoDestino { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
    }
}
