//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadeDeArmazenagemLote
    {
        public UnidadeDeArmazenagemLote()
        {
            this.EstoqueComprasMov = new HashSet<EstoqueComprasMov>();
            this.InventarioUa = new HashSet<InventarioUa>();
            this.MovimentacaoRomaneioItem = new HashSet<MovimentacaoRomaneioItem>();
        }
    
        public int IDUnidadeDeArmazenagemLote { get; set; }
        public int IDUnidadeDeArmazenagem { get; set; }
        public int IDLote { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> Lastro { get; set; }
        public Nullable<decimal> Altura { get; set; }
        public string Divisao { get; set; }
        public Nullable<decimal> SaldoPicking { get; set; }
        public string obs { get; set; }
    
        public virtual ICollection<EstoqueComprasMov> EstoqueComprasMov { get; set; }
        public virtual ICollection<InventarioUa> InventarioUa { get; set; }
        public virtual ICollection<MovimentacaoRomaneioItem> MovimentacaoRomaneioItem { get; set; }
        public virtual UnidadeDeArmazenagem UnidadeDeArmazenagem { get; set; }
    }
}
