//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioClienteDivisao
    {
        public UsuarioClienteDivisao()
        {
            this.CadastroCdaUsuarioClienteDivisao = new HashSet<CadastroCdaUsuarioClienteDivisao>();
        }
    
        public int IDUsuarioClienteDivisao { get; set; }
        public int IDUsuarioCliente { get; set; }
        public int IDClienteDivisao { get; set; }
    
        public virtual ICollection<CadastroCdaUsuarioClienteDivisao> CadastroCdaUsuarioClienteDivisao { get; set; }
        public virtual ClienteDivisao ClienteDivisao { get; set; }
    }
}
