//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioFilial
    {
        public int idUsuarioFilial { get; set; }
        public int IdFilial { get; set; }
        public string Permissao { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual Filial Filial { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual UsuarioFilial UsuarioFilial1 { get; set; }
        public virtual UsuarioFilial UsuarioFilial2 { get; set; }
    }
}
