//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeiculoFoto
    {
        public int IDVeiculoFoto { get; set; }
        public int IDVeiculo { get; set; }
        public byte[] Foto { get; set; }
        public string Descricao { get; set; }
    
        public virtual Veiculo Veiculo { get; set; }
    }
}
