//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistecno.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeiculoModelo
    {
        public VeiculoModelo()
        {
            this.Veiculo = new HashSet<Veiculo>();
        }
    
        public int IDVeiculoModelo { get; set; }
        public int IDVeiculoMarca { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Veiculo> Veiculo { get; set; }
        public virtual VeiculoMarca VeiculoMarca { get; set; }
    }
}
