//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServicosWEB.OL011 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_SYN_OUT_PEDTRANS_INBinding", Namespace="http://star-it.com.br/OperadorLogistico")]
    public partial class SI_SYN_OUT_PEDTRANS_INService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_SYN_OUT_PEDTRANS_INOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_SYN_OUT_PEDTRANS_INService() {
            this.Url = global::ServicosWEB.Properties.Settings.Default.ServicosWEB_OL011_SI_SYN_OUT_PEDTRANS_INService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_SYN_OUT_PEDTRANS_INCompletedEventHandler SI_SYN_OUT_PEDTRANS_INCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_PEDTRANS_IN_RES", Namespace="http://star-it.com.br/OperadorLogistico")]
        public DT_PEDTRANS_IN_RES SI_SYN_OUT_PEDTRANS_IN([System.Xml.Serialization.XmlElementAttribute(Namespace="http://star-it.com.br/OperadorLogistico")] DT_PEDTRANS_IN_REQ MT_PEDTRANS_IN_REQ) {
            object[] results = this.Invoke("SI_SYN_OUT_PEDTRANS_IN", new object[] {
                        MT_PEDTRANS_IN_REQ});
            return ((DT_PEDTRANS_IN_RES)(results[0]));
        }
        
        /// <remarks/>
        public void SI_SYN_OUT_PEDTRANS_INAsync(DT_PEDTRANS_IN_REQ MT_PEDTRANS_IN_REQ) {
            this.SI_SYN_OUT_PEDTRANS_INAsync(MT_PEDTRANS_IN_REQ, null);
        }
        
        /// <remarks/>
        public void SI_SYN_OUT_PEDTRANS_INAsync(DT_PEDTRANS_IN_REQ MT_PEDTRANS_IN_REQ, object userState) {
            if ((this.SI_SYN_OUT_PEDTRANS_INOperationCompleted == null)) {
                this.SI_SYN_OUT_PEDTRANS_INOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_SYN_OUT_PEDTRANS_INOperationCompleted);
            }
            this.InvokeAsync("SI_SYN_OUT_PEDTRANS_IN", new object[] {
                        MT_PEDTRANS_IN_REQ}, this.SI_SYN_OUT_PEDTRANS_INOperationCompleted, userState);
        }
        
        private void OnSI_SYN_OUT_PEDTRANS_INOperationCompleted(object arg) {
            if ((this.SI_SYN_OUT_PEDTRANS_INCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_SYN_OUT_PEDTRANS_INCompleted(this, new SI_SYN_OUT_PEDTRANS_INCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://star-it.com.br/OperadorLogistico")]
    public partial class DT_PEDTRANS_IN_REQ {
        
        private string tIPO_PEDIDOField;
        
        private string pEDIDOField;
        
        private string dATA_PEDField;
        
        private string pEDIDO_ELIMINADOField;
        
        private string fORNECEDORField;
        
        private DT_PEDTRANS_IN_REQITEM[] iTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIPO_PEDIDO {
            get {
                return this.tIPO_PEDIDOField;
            }
            set {
                this.tIPO_PEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PEDIDO {
            get {
                return this.pEDIDOField;
            }
            set {
                this.pEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_PED {
            get {
                return this.dATA_PEDField;
            }
            set {
                this.dATA_PEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PEDIDO_ELIMINADO {
            get {
                return this.pEDIDO_ELIMINADOField;
            }
            set {
                this.pEDIDO_ELIMINADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FORNECEDOR {
            get {
                return this.fORNECEDORField;
            }
            set {
                this.fORNECEDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_PEDTRANS_IN_REQITEM[] ITEM {
            get {
                return this.iTEMField;
            }
            set {
                this.iTEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://star-it.com.br/OperadorLogistico")]
    public partial class DT_PEDTRANS_IN_REQITEM {
        
        private string mATERIALField;
        
        private string dESC_MATField;
        
        private string umField;
        
        private string fATORField;
        
        private string qTDField;
        
        private string cENTROField;
        
        private string iTEM_ELIMINADOField;
        
        private string iTEM_FINALIZADOField;
        
        private string qTD_CONFERIDAField;
        
        private string dATA_VENCField;
        
        private string eMBARQUEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DESC_MAT {
            get {
                return this.dESC_MATField;
            }
            set {
                this.dESC_MATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UM {
            get {
                return this.umField;
            }
            set {
                this.umField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FATOR {
            get {
                return this.fATORField;
            }
            set {
                this.fATORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTD {
            get {
                return this.qTDField;
            }
            set {
                this.qTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CENTRO {
            get {
                return this.cENTROField;
            }
            set {
                this.cENTROField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEM_ELIMINADO {
            get {
                return this.iTEM_ELIMINADOField;
            }
            set {
                this.iTEM_ELIMINADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEM_FINALIZADO {
            get {
                return this.iTEM_FINALIZADOField;
            }
            set {
                this.iTEM_FINALIZADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTD_CONFERIDA {
            get {
                return this.qTD_CONFERIDAField;
            }
            set {
                this.qTD_CONFERIDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_VENC {
            get {
                return this.dATA_VENCField;
            }
            set {
                this.dATA_VENCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMBARQUE {
            get {
                return this.eMBARQUEField;
            }
            set {
                this.eMBARQUEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://star-it.com.br/OperadorLogistico")]
    public partial class DT_PEDTRANS_IN_RES {
        
        private string sTATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SI_SYN_OUT_PEDTRANS_INCompletedEventHandler(object sender, SI_SYN_OUT_PEDTRANS_INCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_SYN_OUT_PEDTRANS_INCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_SYN_OUT_PEDTRANS_INCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_PEDTRANS_IN_RES Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_PEDTRANS_IN_RES)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591