//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5485.
// 
namespace SistecnoColetor.br.com.grupologos.www {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReposcicaoRogeSoap", Namespace="http://tempuri.org/")]
    public partial class ReposcicaoRoge : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ReposcicaoRoge() {
            this.Url = "http://www.grupologos.com.br/wss/WSS/ReposicaoRoge.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GravarDocumento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GravarDocumento(string Chave, string CodigoRegiao, string NomeRegiao, string ClienteEspecial, Volumes[] Volume, Itens[] Item) {
            object[] results = this.Invoke("GravarDocumento", new object[] {
                        Chave,
                        CodigoRegiao,
                        NomeRegiao,
                        ClienteEspecial,
                        Volume,
                        Item});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGravarDocumento(string Chave, string CodigoRegiao, string NomeRegiao, string ClienteEspecial, Volumes[] Volume, Itens[] Item, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GravarDocumento", new object[] {
                        Chave,
                        CodigoRegiao,
                        NomeRegiao,
                        ClienteEspecial,
                        Volume,
                        Item}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGravarDocumento(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelarConferencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CancelarConferencia(string Chave, string UsuarioSolicitante) {
            object[] results = this.Invoke("CancelarConferencia", new object[] {
                        Chave,
                        UsuarioSolicitante});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCancelarConferencia(string Chave, string UsuarioSolicitante, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CancelarConferencia", new object[] {
                        Chave,
                        UsuarioSolicitante}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCancelarConferencia(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResgatarDocumentoPeloColetor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ResgatarDocumentoPeloColetor(string Chave, string IdUsuario) {
            object[] results = this.Invoke("ResgatarDocumentoPeloColetor", new object[] {
                        Chave,
                        IdUsuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginResgatarDocumentoPeloColetor(string Chave, string IdUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ResgatarDocumentoPeloColetor", new object[] {
                        Chave,
                        IdUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndResgatarDocumentoPeloColetor(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GravarConferencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GravarConferencia(Estrutura[] Dados) {
            this.Invoke("GravarConferencia", new object[] {
                        Dados});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGravarConferencia(Estrutura[] Dados, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GravarConferencia", new object[] {
                        Dados}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGravarConferencia(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Volumes {
        
        private string codigoBarrasField;
        
        /// <remarks/>
        public string CodigoBarras {
            get {
                return this.codigoBarrasField;
            }
            set {
                this.codigoBarrasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Estrutura {
        
        private string volumeCodigoBarrasField;
        
        private string itemCodigoBarrasField;
        
        private string cB_LIDOField;
        
        /// <remarks/>
        public string VolumeCodigoBarras {
            get {
                return this.volumeCodigoBarrasField;
            }
            set {
                this.volumeCodigoBarrasField = value;
            }
        }
        
        /// <remarks/>
        public string ItemCodigoBarras {
            get {
                return this.itemCodigoBarrasField;
            }
            set {
                this.itemCodigoBarrasField = value;
            }
        }
        
        /// <remarks/>
        public string CB_LIDO {
            get {
                return this.cB_LIDOField;
            }
            set {
                this.cB_LIDOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CodigoBarras {
        
        private string codigoDeBarrasField;
        
        private string embalagemField;
        
        private string embalagemQuantidadeField;
        
        /// <remarks/>
        public string CodigoDeBarras {
            get {
                return this.codigoDeBarrasField;
            }
            set {
                this.codigoDeBarrasField = value;
            }
        }
        
        /// <remarks/>
        public string Embalagem {
            get {
                return this.embalagemField;
            }
            set {
                this.embalagemField = value;
            }
        }
        
        /// <remarks/>
        public string EmbalagemQuantidade {
            get {
                return this.embalagemQuantidadeField;
            }
            set {
                this.embalagemQuantidadeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Itens {
        
        private int codigoRogeField;
        
        private int quantidadeField;
        
        private CodigoBarras[] itensCodigoBarrasField;
        
        /// <remarks/>
        public int CodigoRoge {
            get {
                return this.codigoRogeField;
            }
            set {
                this.codigoRogeField = value;
            }
        }
        
        /// <remarks/>
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public CodigoBarras[] ItensCodigoBarras {
            get {
                return this.itensCodigoBarrasField;
            }
            set {
                this.itensCodigoBarrasField = value;
            }
        }
    }
}
