//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DbUpdateCompusoft.TesteWs {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsSoap", Namespace="http://tempuri.org/")]
    public partial class ws : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReceberPedidosOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornarStatusPedidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EstoqueOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ws() {
            this.Url = global::DbUpdateCompusoft.Properties.Settings.Default.DbUpdateCompusoft_TesteWs_ws;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReceberPedidosCompletedEventHandler ReceberPedidosCompleted;
        
        /// <remarks/>
        public event RetornarStatusPedidoCompletedEventHandler RetornarStatusPedidoCompleted;
        
        /// <remarks/>
        public event EstoqueCompletedEventHandler EstoqueCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReceberPedidos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReceberPedidos(string Login, string Senha, Pedido[] pedido, string prod_hom, string TipoDePedido, string CNPJdoCliente) {
            object[] results = this.Invoke("ReceberPedidos", new object[] {
                        Login,
                        Senha,
                        pedido,
                        prod_hom,
                        TipoDePedido,
                        CNPJdoCliente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReceberPedidosAsync(string Login, string Senha, Pedido[] pedido, string prod_hom, string TipoDePedido, string CNPJdoCliente) {
            this.ReceberPedidosAsync(Login, Senha, pedido, prod_hom, TipoDePedido, CNPJdoCliente, null);
        }
        
        /// <remarks/>
        public void ReceberPedidosAsync(string Login, string Senha, Pedido[] pedido, string prod_hom, string TipoDePedido, string CNPJdoCliente, object userState) {
            if ((this.ReceberPedidosOperationCompleted == null)) {
                this.ReceberPedidosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceberPedidosOperationCompleted);
            }
            this.InvokeAsync("ReceberPedidos", new object[] {
                        Login,
                        Senha,
                        pedido,
                        prod_hom,
                        TipoDePedido,
                        CNPJdoCliente}, this.ReceberPedidosOperationCompleted, userState);
        }
        
        private void OnReceberPedidosOperationCompleted(object arg) {
            if ((this.ReceberPedidosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceberPedidosCompleted(this, new ReceberPedidosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornarStatusPedido", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RetornoPedidoStatus RetornarStatusPedido(string Login, string Senha, string Cnpj, int NrPedido) {
            object[] results = this.Invoke("RetornarStatusPedido", new object[] {
                        Login,
                        Senha,
                        Cnpj,
                        NrPedido});
            return ((RetornoPedidoStatus)(results[0]));
        }
        
        /// <remarks/>
        public void RetornarStatusPedidoAsync(string Login, string Senha, string Cnpj, int NrPedido) {
            this.RetornarStatusPedidoAsync(Login, Senha, Cnpj, NrPedido, null);
        }
        
        /// <remarks/>
        public void RetornarStatusPedidoAsync(string Login, string Senha, string Cnpj, int NrPedido, object userState) {
            if ((this.RetornarStatusPedidoOperationCompleted == null)) {
                this.RetornarStatusPedidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornarStatusPedidoOperationCompleted);
            }
            this.InvokeAsync("RetornarStatusPedido", new object[] {
                        Login,
                        Senha,
                        Cnpj,
                        NrPedido}, this.RetornarStatusPedidoOperationCompleted, userState);
        }
        
        private void OnRetornarStatusPedidoOperationCompleted(object arg) {
            if ((this.RetornarStatusPedidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornarStatusPedidoCompleted(this, new RetornarStatusPedidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Estoque", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Estoque(string login, string senha) {
            object[] results = this.Invoke("Estoque", new object[] {
                        login,
                        senha});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void EstoqueAsync(string login, string senha) {
            this.EstoqueAsync(login, senha, null);
        }
        
        /// <remarks/>
        public void EstoqueAsync(string login, string senha, object userState) {
            if ((this.EstoqueOperationCompleted == null)) {
                this.EstoqueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstoqueOperationCompleted);
            }
            this.InvokeAsync("Estoque", new object[] {
                        login,
                        senha}, this.EstoqueOperationCompleted, userState);
        }
        
        private void OnEstoqueOperationCompleted(object arg) {
            if ((this.EstoqueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstoqueCompleted(this, new EstoqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pedido {
        
        private string cliente_CNPJField;
        
        private string tipoDeDocumentoField;
        
        private System.DateTime dataDeEmissaoField;
        
        private string numeroDocumentoField;
        
        private string serieField;
        
        private string dest_CNPJCPFField;
        
        private string dest_IERGField;
        
        private string dest_RAZAOSOCIALField;
        
        private string dest_FANTASIAField;
        
        private string dest_ENDERECOField;
        
        private string dest_NUMEROField;
        
        private string dest_COMPLEMENTOField;
        
        private string dest_BAIRROField;
        
        private string dest_COD_IBGE_CIDADEField;
        
        private string dest_CIDADE_NOMEField;
        
        private string dest_CEPField;
        
        private string dest_ENTREGA_CEPField;
        
        private string dest_ENTREGA_ENDERECOField;
        
        private string dest_ENTREGA_NUMEROField;
        
        private string dest_ENTREGA_COMPLEMENTOField;
        
        private string dest_ENTREGA_BAIRROField;
        
        private string dest_ENTREGA_COD_IBGE_CIDADEField;
        
        private string dest_EmailField;
        
        private string dest_TelefoneField;
        
        private string dataParaEntregaField;
        
        private string compraVendaField;
        
        private string periodoDeEntregaInicioField;
        
        private string periodoDeEntregaFimField;
        
        private Itens[] itensField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        /// <remarks/>
        public string Cliente_CNPJ {
            get {
                return this.cliente_CNPJField;
            }
            set {
                this.cliente_CNPJField = value;
            }
        }
        
        /// <remarks/>
        public string TipoDeDocumento {
            get {
                return this.tipoDeDocumentoField;
            }
            set {
                this.tipoDeDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataDeEmissao {
            get {
                return this.dataDeEmissaoField;
            }
            set {
                this.dataDeEmissaoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_CNPJCPF {
            get {
                return this.dest_CNPJCPFField;
            }
            set {
                this.dest_CNPJCPFField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_IERG {
            get {
                return this.dest_IERGField;
            }
            set {
                this.dest_IERGField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_RAZAOSOCIAL {
            get {
                return this.dest_RAZAOSOCIALField;
            }
            set {
                this.dest_RAZAOSOCIALField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_FANTASIA {
            get {
                return this.dest_FANTASIAField;
            }
            set {
                this.dest_FANTASIAField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_ENDERECO {
            get {
                return this.dest_ENDERECOField;
            }
            set {
                this.dest_ENDERECOField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_NUMERO {
            get {
                return this.dest_NUMEROField;
            }
            set {
                this.dest_NUMEROField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_COMPLEMENTO {
            get {
                return this.dest_COMPLEMENTOField;
            }
            set {
                this.dest_COMPLEMENTOField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_BAIRRO {
            get {
                return this.dest_BAIRROField;
            }
            set {
                this.dest_BAIRROField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_COD_IBGE_CIDADE {
            get {
                return this.dest_COD_IBGE_CIDADEField;
            }
            set {
                this.dest_COD_IBGE_CIDADEField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_CIDADE_NOME {
            get {
                return this.dest_CIDADE_NOMEField;
            }
            set {
                this.dest_CIDADE_NOMEField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_CEP {
            get {
                return this.dest_CEPField;
            }
            set {
                this.dest_CEPField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_ENTREGA_CEP {
            get {
                return this.dest_ENTREGA_CEPField;
            }
            set {
                this.dest_ENTREGA_CEPField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_ENTREGA_ENDERECO {
            get {
                return this.dest_ENTREGA_ENDERECOField;
            }
            set {
                this.dest_ENTREGA_ENDERECOField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_ENTREGA_NUMERO {
            get {
                return this.dest_ENTREGA_NUMEROField;
            }
            set {
                this.dest_ENTREGA_NUMEROField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_ENTREGA_COMPLEMENTO {
            get {
                return this.dest_ENTREGA_COMPLEMENTOField;
            }
            set {
                this.dest_ENTREGA_COMPLEMENTOField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_ENTREGA_BAIRRO {
            get {
                return this.dest_ENTREGA_BAIRROField;
            }
            set {
                this.dest_ENTREGA_BAIRROField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_ENTREGA_COD_IBGE_CIDADE {
            get {
                return this.dest_ENTREGA_COD_IBGE_CIDADEField;
            }
            set {
                this.dest_ENTREGA_COD_IBGE_CIDADEField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_Email {
            get {
                return this.dest_EmailField;
            }
            set {
                this.dest_EmailField = value;
            }
        }
        
        /// <remarks/>
        public string Dest_Telefone {
            get {
                return this.dest_TelefoneField;
            }
            set {
                this.dest_TelefoneField = value;
            }
        }
        
        /// <remarks/>
        public string DataParaEntrega {
            get {
                return this.dataParaEntregaField;
            }
            set {
                this.dataParaEntregaField = value;
            }
        }
        
        /// <remarks/>
        public string CompraVenda {
            get {
                return this.compraVendaField;
            }
            set {
                this.compraVendaField = value;
            }
        }
        
        /// <remarks/>
        public string PeriodoDeEntregaInicio {
            get {
                return this.periodoDeEntregaInicioField;
            }
            set {
                this.periodoDeEntregaInicioField = value;
            }
        }
        
        /// <remarks/>
        public string PeriodoDeEntregaFim {
            get {
                return this.periodoDeEntregaFimField;
            }
            set {
                this.periodoDeEntregaFimField = value;
            }
        }
        
        /// <remarks/>
        public Itens[] itens {
            get {
                return this.itensField;
            }
            set {
                this.itensField = value;
            }
        }
        
        /// <remarks/>
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Itens {
        
        private string sKUField;
        
        private string descricaoField;
        
        private string eANField;
        
        private string codigoNCMField;
        
        private int quantidadeField;
        
        private decimal valorUnitarioField;
        
        private decimal pesoLiquidoField;
        
        /// <remarks/>
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public string EAN {
            get {
                return this.eANField;
            }
            set {
                this.eANField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoNCM {
            get {
                return this.codigoNCMField;
            }
            set {
                this.codigoNCMField = value;
            }
        }
        
        /// <remarks/>
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorUnitario {
            get {
                return this.valorUnitarioField;
            }
            set {
                this.valorUnitarioField = value;
            }
        }
        
        /// <remarks/>
        public decimal PesoLiquido {
            get {
                return this.pesoLiquidoField;
            }
            set {
                this.pesoLiquidoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RetornoPedidoStatusItem {
        
        private int idField;
        
        private int idStatusPedidoField;
        
        private string codigoDoProdutoField;
        
        private int quantidadeField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int IdStatusPedido {
            get {
                return this.idStatusPedidoField;
            }
            set {
                this.idStatusPedidoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoDoProduto {
            get {
                return this.codigoDoProdutoField;
            }
            set {
                this.codigoDoProdutoField = value;
            }
        }
        
        /// <remarks/>
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RetornoPedidoStatus {
        
        private int idField;
        
        private int nrPedidoField;
        
        private string statusField;
        
        private string consumidoField;
        
        private System.DateTime dataHoraField;
        
        private RetornoPedidoStatusItem[] itemsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int NrPedido {
            get {
                return this.nrPedidoField;
            }
            set {
                this.nrPedidoField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Consumido {
            get {
                return this.consumidoField;
            }
            set {
                this.consumidoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataHora {
            get {
                return this.dataHoraField;
            }
            set {
                this.dataHoraField = value;
            }
        }
        
        /// <remarks/>
        public RetornoPedidoStatusItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ReceberPedidosCompletedEventHandler(object sender, ReceberPedidosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceberPedidosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceberPedidosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RetornarStatusPedidoCompletedEventHandler(object sender, RetornarStatusPedidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornarStatusPedidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornarStatusPedidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetornoPedidoStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetornoPedidoStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EstoqueCompletedEventHandler(object sender, EstoqueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EstoqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstoqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591